---
title: "Social Justice in Statistics and Data Science: Project Page"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmdformats)
```

# Project Contributors

In alphabetical order: 

- Nina Bailey
- John Bartucz
- Carlos Chavez
- [V.N. Vimal Rao](https://raovnv.github.io/research.html)

# Introduction to the Project

In harnessing the power of data, statistics educators have begun to develop curricula that situates data science and statistics as a tool for social justice. However, successfully implementing these curricula requires unique considerations for the management of the classroom learning environment. 

# ECOTS 2022

We hosted a [Breakout Session](https://causeweb.org/cause/ecots/ecots22/program/breakout/12) at the 2022 Electronic Conference on Teaching Statistics in which we shared our experiences and recommendations in a Panel Question & Answer session. The title of the session was "Social Justice Is More Than Just Using Critical Contexts: Embedding Social Justice into Curricula". [Here](https://docs.google.com/document/d/1fJ03KRQ0AEtI3tCLiG4drMFGnidgFV6KZZTVeY3YHEQ/edit?usp=sharing) are some notes from the session. 

Additional resources for our session can be found here:

- Nina's [difficult discussion role playing](https://docs.google.com/document/d/11UNy3y__asovhnQxfA8lcPeWj3pBLVlgEtYWyzunODg/edit?usp=sharing)
- John's district's [Equity Statements](https://www.rochesterschools.org/equity-statement)
- Nina's [Preparing to Discuss Issues of Equity Survey](https://docs.google.com/forms/d/e/1FAIpQLSdIZ3oE7faDTxQHhHMOksJEj_ruy6VmamaRyFuWR3S7hC_qVw/viewform) 

# Upcoming Paper in Preparation

We are currently working on a paper that will provide recommendations, activities, and additional resources for instructors. Stay tuned!
